---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-system-github
  description: test-system-github
spec:
  owner: skitamura-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-system-gitlab
  description: test-system-gitlab
spec:
  owner: skitamura-team-gitlab
